/* Generated By:JJTree&JavaCC: Do not edit this line. CCJSqlParserConstants.java */
/*
 * #%L
 * JSQLParser library
 * %%
 * Copyright (C) 2004 - 2014 JSQLParser
 * %%
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation, either version 2.1 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Lesser Public License for more details.
 *
 * You should have received a copy of the GNU General Lesser Public
 * License along with this program.  If not, see
 * <http://www.gnu.org/licenses/lgpl-2.1.html>.
 * #L%
 */

package net.sf.jsqlparser.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CCJSqlParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int WHITESPACE = 1;
  /** RegularExpression Id. */
  int K_AS = 2;
  /** RegularExpression Id. */
  int K_BY = 3;
  /** RegularExpression Id. */
  int K_DO = 4;
  /** RegularExpression Id. */
  int K_IS = 5;
  /** RegularExpression Id. */
  int K_IN = 6;
  /** RegularExpression Id. */
  int K_OR = 7;
  /** RegularExpression Id. */
  int K_ON = 8;
  /** RegularExpression Id. */
  int K_ALL = 9;
  /** RegularExpression Id. */
  int K_AND = 10;
  /** RegularExpression Id. */
  int K_ANY = 11;
  /** RegularExpression Id. */
  int K_KEY = 12;
  /** RegularExpression Id. */
  int K_NOT = 13;
  /** RegularExpression Id. */
  int K_SET = 14;
  /** RegularExpression Id. */
  int K_ASC = 15;
  /** RegularExpression Id. */
  int K_TOP = 16;
  /** RegularExpression Id. */
  int K_PERCENT = 17;
  /** RegularExpression Id. */
  int K_END = 18;
  /** RegularExpression Id. */
  int K_DESC = 19;
  /** RegularExpression Id. */
  int K_INTO = 20;
  /** RegularExpression Id. */
  int K_NULL = 21;
  /** RegularExpression Id. */
  int K_LIKE = 22;
  /** RegularExpression Id. */
  int K_ILIKE = 23;
  /** RegularExpression Id. */
  int K_DROP = 24;
  /** RegularExpression Id. */
  int K_JOIN = 25;
  /** RegularExpression Id. */
  int K_LEFT = 26;
  /** RegularExpression Id. */
  int K_CROSS = 27;
  /** RegularExpression Id. */
  int K_FROM = 28;
  /** RegularExpression Id. */
  int K_OPEN = 29;
  /** RegularExpression Id. */
  int K_CASE = 30;
  /** RegularExpression Id. */
  int K_WHEN = 31;
  /** RegularExpression Id. */
  int K_THEN = 32;
  /** RegularExpression Id. */
  int K_ELSE = 33;
  /** RegularExpression Id. */
  int K_SOME = 34;
  /** RegularExpression Id. */
  int K_FULL = 35;
  /** RegularExpression Id. */
  int K_WITH = 36;
  /** RegularExpression Id. */
  int K_TABLE = 37;
  /** RegularExpression Id. */
  int K_VIEW = 38;
  /** RegularExpression Id. */
  int K_WHERE = 39;
  /** RegularExpression Id. */
  int K_FOR = 40;
  /** RegularExpression Id. */
  int K_PIVOT = 41;
  /** RegularExpression Id. */
  int K_XML = 42;
  /** RegularExpression Id. */
  int K_USING = 43;
  /** RegularExpression Id. */
  int K_UNION = 44;
  /** RegularExpression Id. */
  int K_GROUP = 45;
  /** RegularExpression Id. */
  int K_BEGIN = 46;
  /** RegularExpression Id. */
  int K_INDEX = 47;
  /** RegularExpression Id. */
  int K_INNER = 48;
  /** RegularExpression Id. */
  int K_LIMIT = 49;
  /** RegularExpression Id. */
  int K_OUTER = 50;
  /** RegularExpression Id. */
  int K_ORDER = 51;
  /** RegularExpression Id. */
  int K_RIGHT = 52;
  /** RegularExpression Id. */
  int K_VALUE = 53;
  /** RegularExpression Id. */
  int K_DELETE = 54;
  /** RegularExpression Id. */
  int K_CREATE = 55;
  /** RegularExpression Id. */
  int K_SELECT = 56;
  /** RegularExpression Id. */
  int K_OFFSET = 57;
  /** RegularExpression Id. */
  int K_EXISTS = 58;
  /** RegularExpression Id. */
  int K_HAVING = 59;
  /** RegularExpression Id. */
  int K_INSERT = 60;
  /** RegularExpression Id. */
  int K_UPDATE = 61;
  /** RegularExpression Id. */
  int K_VALUES = 62;
  /** RegularExpression Id. */
  int K_ESCAPE = 63;
  /** RegularExpression Id. */
  int K_PRIMARY = 64;
  /** RegularExpression Id. */
  int K_FULLTEXT = 65;
  /** RegularExpression Id. */
  int K_NATURAL = 66;
  /** RegularExpression Id. */
  int K_REPLACE = 67;
  /** RegularExpression Id. */
  int K_BETWEEN = 68;
  /** RegularExpression Id. */
  int K_TRUNCATE = 69;
  /** RegularExpression Id. */
  int K_DISTINCT = 70;
  /** RegularExpression Id. */
  int K_INTERSECT = 71;
  /** RegularExpression Id. */
  int K_CAST = 72;
  /** RegularExpression Id. */
  int K_EXCEPT = 73;
  /** RegularExpression Id. */
  int K_MINUS = 74;
  /** RegularExpression Id. */
  int K_OVER = 75;
  /** RegularExpression Id. */
  int K_PARTITION = 76;
  /** RegularExpression Id. */
  int K_EXTRACT = 77;
  /** RegularExpression Id. */
  int K_LATERAL = 78;
  /** RegularExpression Id. */
  int K_MATERIALIZED = 79;
  /** RegularExpression Id. */
  int K_INTERVAL = 80;
  /** RegularExpression Id. */
  int K_FOREIGN = 81;
  /** RegularExpression Id. */
  int K_CONSTRAINT = 82;
  /** RegularExpression Id. */
  int K_REFERENCES = 83;
  /** RegularExpression Id. */
  int K_CHECK = 84;
  /** RegularExpression Id. */
  int K_CHARACTER = 85;
  /** RegularExpression Id. */
  int K_VARYING = 86;
  /** RegularExpression Id. */
  int K_START = 87;
  /** RegularExpression Id. */
  int K_CONNECT = 88;
  /** RegularExpression Id. */
  int K_PRIOR = 89;
  /** RegularExpression Id. */
  int K_NOCYCLE = 90;
  /** RegularExpression Id. */
  int K_SIBLINGS = 91;
  /** RegularExpression Id. */
  int K_ALTER = 92;
  /** RegularExpression Id. */
  int K_ADD = 93;
  /** RegularExpression Id. */
  int K_COLUMN = 94;
  /** RegularExpression Id. */
  int K_NULLS = 95;
  /** RegularExpression Id. */
  int K_FIRST = 96;
  /** RegularExpression Id. */
  int K_LAST = 97;
  /** RegularExpression Id. */
  int K_ROWS = 98;
  /** RegularExpression Id. */
  int K_RANGE = 99;
  /** RegularExpression Id. */
  int K_UNBOUNDED = 100;
  /** RegularExpression Id. */
  int K_PRECEDING = 101;
  /** RegularExpression Id. */
  int K_FOLLOWING = 102;
  /** RegularExpression Id. */
  int K_CURRENT = 103;
  /** RegularExpression Id. */
  int K_ROW = 104;
  /** RegularExpression Id. */
  int K_RETURNING = 105;
  /** RegularExpression Id. */
  int K_BINARY = 106;
  /** RegularExpression Id. */
  int K_REGEXP = 107;
  /** RegularExpression Id. */
  int K_UNLOGGED = 108;
  /** RegularExpression Id. */
  int K_EXEC = 109;
  /** RegularExpression Id. */
  int K_EXECUTE = 110;
  /** RegularExpression Id. */
  int K_FETCH = 111;
  /** RegularExpression Id. */
  int K_NEXT = 112;
  /** RegularExpression Id. */
  int K_ONLY = 113;
  /** RegularExpression Id. */
  int K_COMMIT = 114;
  /** RegularExpression Id. */
  int K_UNIQUE = 115;
  /** RegularExpression Id. */
  int K_WITHIN = 116;
  /** RegularExpression Id. */
  int K_IF = 117;
  /** RegularExpression Id. */
  int K_RECURSIVE = 118;
  /** RegularExpression Id. */
  int K_OF = 119;
  /** RegularExpression Id. */
  int K_KEEP = 120;
  /** RegularExpression Id. */
  int K_GROUP_CONCAT = 121;
  /** RegularExpression Id. */
  int K_SEPARATOR = 122;
  /** RegularExpression Id. */
  int K_SKIP = 123;
  /** RegularExpression Id. */
  int K_MERGE = 124;
  /** RegularExpression Id. */
  int K_MATCHED = 125;
  /** RegularExpression Id. */
  int K_CASCADE = 126;
  /** RegularExpression Id. */
  int K_RESTRICT = 127;
  /** RegularExpression Id. */
  int K_NO = 128;
  /** RegularExpression Id. */
  int K_ACTION = 129;
  /** RegularExpression Id. */
  int K_DUPLICATE = 130;
  /** RegularExpression Id. */
  int K_LOW_PRIORITY = 131;
  /** RegularExpression Id. */
  int K_DELAYED = 132;
  /** RegularExpression Id. */
  int K_HIGH_PRIORITY = 133;
  /** RegularExpression Id. */
  int K_IGNORE = 134;
  /** RegularExpression Id. */
  int K_SEMI = 135;
  /** RegularExpression Id. */
  int K_DATETIMELITERAL = 136;
  /** RegularExpression Id. */
  int K_TIME_KEY_EXPR = 137;
  /** RegularExpression Id. */
  int K_DOUBLE = 138;
  /** RegularExpression Id. */
  int K_PRECISION = 139;
  /** RegularExpression Id. */
  int K_TABLESPACE = 140;
  /** RegularExpression Id. */
  int ST_SEMICOLON = 141;
  /** RegularExpression Id. */
  int OP_GREATERTHANEQUALS = 142;
  /** RegularExpression Id. */
  int OP_MINORTHANEQUALS = 143;
  /** RegularExpression Id. */
  int OP_NOTEQUALSSTANDARD = 144;
  /** RegularExpression Id. */
  int OP_NOTEQUALSBANG = 145;
  /** RegularExpression Id. */
  int S_DOUBLE = 146;
  /** RegularExpression Id. */
  int S_LONG = 147;
  /** RegularExpression Id. */
  int DIGIT = 148;
  /** RegularExpression Id. */
  int S_HEX = 149;
  /** RegularExpression Id. */
  int HEX_VALUE = 150;
  /** RegularExpression Id. */
  int LINE_COMMENT = 151;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 152;
  /** RegularExpression Id. */
  int S_IDENTIFIER = 153;
  /** RegularExpression Id. */
  int LETTER = 154;
  /** RegularExpression Id. */
  int PART_LETTER = 155;
  /** RegularExpression Id. */
  int S_CHAR_LITERAL = 156;
  /** RegularExpression Id. */
  int S_QUOTED_IDENTIFIER = 157;
  /** RegularExpression Id. */
  int ESC = 158;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<WHITESPACE>",
    "\"AS\"",
    "\"BY\"",
    "\"DO\"",
    "\"IS\"",
    "\"IN\"",
    "\"OR\"",
    "\"ON\"",
    "\"ALL\"",
    "\"AND\"",
    "\"ANY\"",
    "\"KEY\"",
    "\"NOT\"",
    "\"SET\"",
    "\"ASC\"",
    "\"TOP\"",
    "\"PERCENT\"",
    "\"END\"",
    "\"DESC\"",
    "\"INTO\"",
    "\"NULL\"",
    "\"LIKE\"",
    "\"ILIKE\"",
    "\"DROP\"",
    "\"JOIN\"",
    "\"LEFT\"",
    "\"CROSS\"",
    "\"FROM\"",
    "\"OPEN\"",
    "\"CASE\"",
    "\"WHEN\"",
    "\"THEN\"",
    "\"ELSE\"",
    "\"SOME\"",
    "\"FULL\"",
    "\"WITH\"",
    "\"TABLE\"",
    "\"VIEW\"",
    "\"WHERE\"",
    "\"FOR\"",
    "\"PIVOT\"",
    "\"XML\"",
    "\"USING\"",
    "\"UNION\"",
    "\"GROUP\"",
    "\"BEGIN\"",
    "\"INDEX\"",
    "\"INNER\"",
    "\"LIMIT\"",
    "\"OUTER\"",
    "\"ORDER\"",
    "\"RIGHT\"",
    "\"VALUE\"",
    "\"DELETE\"",
    "\"CREATE\"",
    "\"SELECT\"",
    "\"OFFSET\"",
    "\"EXISTS\"",
    "\"HAVING\"",
    "\"INSERT\"",
    "\"UPDATE\"",
    "\"VALUES\"",
    "\"ESCAPE\"",
    "\"PRIMARY\"",
    "\"FULLTEXT\"",
    "\"NATURAL\"",
    "\"REPLACE\"",
    "\"BETWEEN\"",
    "\"TRUNCATE\"",
    "\"DISTINCT\"",
    "\"INTERSECT\"",
    "\"CAST\"",
    "\"EXCEPT\"",
    "\"MINUS\"",
    "\"OVER\"",
    "\"PARTITION\"",
    "\"EXTRACT\"",
    "\"LATERAL\"",
    "\"MATERIALIZED\"",
    "\"INTERVAL\"",
    "\"FOREIGN\"",
    "\"CONSTRAINT\"",
    "\"REFERENCES\"",
    "\"CHECK\"",
    "\"CHARACTER\"",
    "\"VARYING\"",
    "\"START\"",
    "\"CONNECT\"",
    "\"PRIOR\"",
    "\"NOCYCLE\"",
    "\"SIBLINGS\"",
    "\"ALTER\"",
    "\"ADD\"",
    "\"COLUMN\"",
    "\"NULLS\"",
    "\"FIRST\"",
    "\"LAST\"",
    "\"ROWS\"",
    "\"RANGE\"",
    "\"UNBOUNDED\"",
    "\"PRECEDING\"",
    "\"FOLLOWING\"",
    "\"CURRENT\"",
    "\"ROW\"",
    "\"RETURNING\"",
    "\"BINARY\"",
    "\"REGEXP\"",
    "\"UNLOGGED\"",
    "\"EXEC\"",
    "\"EXECUTE\"",
    "\"FETCH\"",
    "\"NEXT\"",
    "\"ONLY\"",
    "\"COMMIT\"",
    "\"UNIQUE\"",
    "\"WITHIN\"",
    "\"IF\"",
    "\"RECURSIVE\"",
    "\"OF\"",
    "\"KEEP\"",
    "\"GROUP_CONCAT\"",
    "\"SEPARATOR\"",
    "\"SKIP\"",
    "\"MERGE\"",
    "\"MATCHED\"",
    "\"CASCADE\"",
    "\"RESTRICT\"",
    "\"NO\"",
    "\"ACTION\"",
    "\"DUPLICATE\"",
    "\"LOW_PRIORITY\"",
    "\"DELAYED\"",
    "\"HIGH_PRIORITY\"",
    "\"IGNORE\"",
    "\"SEMI\"",
    "<K_DATETIMELITERAL>",
    "<K_TIME_KEY_EXPR>",
    "\"DOUBLE\"",
    "\"PRECISION\"",
    "\"TABLESPACE\"",
    "\";\"",
    "<OP_GREATERTHANEQUALS>",
    "<OP_MINORTHANEQUALS>",
    "<OP_NOTEQUALSSTANDARD>",
    "\"!=\"",
    "<S_DOUBLE>",
    "<S_LONG>",
    "<DIGIT>",
    "<S_HEX>",
    "<HEX_VALUE>",
    "<LINE_COMMENT>",
    "<MULTI_LINE_COMMENT>",
    "<S_IDENTIFIER>",
    "<LETTER>",
    "<PART_LETTER>",
    "<S_CHAR_LITERAL>",
    "<S_QUOTED_IDENTIFIER>",
    "<ESC>",
    "\"=\"",
    "\",\"",
    "\"(\"",
    "\")\"",
    "\"*\"",
    "\".\"",
    "\"?\"",
    "\"+\"",
    "\">\"",
    "\"<\"",
    "\"@@\"",
    "\"~\"",
    "\"~*\"",
    "\"!~\"",
    "\"!~*\"",
    "\"||\"",
    "\"|\"",
    "\"&\"",
    "\"-\"",
    "\"/\"",
    "\"%\"",
    "\"^\"",
    "\"{d\"",
    "\"}\"",
    "\"{t\"",
    "\"{ts\"",
    "\"::\"",
    "\":\"",
    "\"@\"",
    "\"->\"",
    "\"{fn\"",
    "\"[\"",
    "\"]\"",
  };

}
