/* Generated By:JavaCC: Do not edit this line. SQLParserVisitor.java Version 5.0 */
package net.sf.jsqlparser.parser;

public interface SQLParserVisitor
{
  public Object visit(SimpleNode node, Object data);
}
/* JavaCC - OriginalChecksum=2099d3f953c77c2a5e61a0ef8904a261 (do not edit this line) */
